apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden-k8s-sync
  namespace: vaultwarden-sync
  labels:
    app.kubernetes.io/name: vaultwarden-k8s-sync
    app.kubernetes.io/managed-by: vaultwarden-k8s-sync
